version: "2.1"

services:
  mariadb3:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb3
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=password123
      - TZ=America/Los_Angeles
    volumes:
      - ./.db:/config
    restart: unless-stopped

  baseball:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    image: baseball
    volumes:
      - "./output:/app/files"
    command: ["/bin/bash", "hw6.sh"]
